In [23]:
import pandas as pd
import numpy as np

QUESTION 1

In [2]:
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [7]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [8]:
df.tail()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

QUESTION 2

In [27]:
df.shape

(10000, 11)

QUESTION 3

In [25]:
df["fuel_type"].nunique()

3

QUESTION 4

In [18]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

QUESTION 5

In [19]:
df[df.origin == "Asia"].fuel_efficiency_mpg.max()

np.float64(41.2)

QUESTION 6

In [20]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [21]:
#to check for any missing values
df.horsepower = df.horsepower.fillna(df.horsepower.mode()[0])

In [22]:
df.horsepower.median()

np.float64(252.0)

QUESTION 7

In [24]:
# Select the first 7 cars from Asia
asia_cars = df[df["origin"] == "Asia"].head(7)

# Create the X matrix using vehicle_weight and model_year
X = asia_cars[["vehicle_weight", "model_year"]].values

# Create the target vector
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Calculate X^T X
XTX = X.T @ X

# Calculate the inverse of X^T X
XTX_inv = np.linalg.inv(XTX)

# Calculate the weights
w = XTX_inv @ X.T @ y

# Calculate the sum of the weights
w_sum = w.sum()

print("Weights:", w)
print("Sum of weights:", w_sum)

Weights: [0.13644777 0.2327492 ]
Sum of weights: 0.36919696904925486